{'childExercises': [
                              {'githubLink': 'https://github.com/navgurukul/newton/tree/master/html/navgurukul-ka-brochure/part1.md',
                               'id': 888,
                               'name': 'Part One',
                               'parentExerciseId': 880,
                               'reviewType': 'peer',
                               'sequenceNum': 1001,
                               'slug': 'html__navgurukul-ka-brochure/part1',
                               'submissionType': None},
                              {'githubLink': 'https://github.com/navgurukul/newton/tree/master/html/navgurukul-ka-brochure/part2.md',
                               'id': 889,
                               'name': 'Part Two',
                               'parentExerciseId': 880,
                               'reviewType': 'peer',
                               'sequenceNum': 1002,
                               'slug': 'html__navgurukul-ka-brochure/part2',
                               'submissionType': None},
                              {'githubLink': 'https://github.com/navgurukul/newton/tree/master/html/navgurukul-ka-brochure/part3.md',
                               'id': 885,
                               'name': 'Part Three',
                               'parentExerciseId': 880,
                               'reviewType': 'peer',
                               'sequenceNum': 1003,
                               'slug': 'html__navgurukul-ka-brochure/part3',
                               'submissionType': None},
                              {'githubLink': 'https://github.com/navgurukul/newton/tree/master/html/navgurukul-ka-brochure/part4.md',
                               'id': 886,
                               'name': 'Part Four',
                               'parentExerciseId': 880,
                               'reviewType': 'peer',
                               'sequenceNum': 1004,
                               'slug': 'html__navgurukul-ka-brochure/part4',
                               'submissionType': None},
                              {'githubLink': 'https://github.com/navgurukul/newton/tree/master/html/navgurukul-ka-brochure/part5.md',
                               'id': 887,
                               'name': 'Part Five',
                               'parentExerciseId': 880,
                               'reviewType': 'peer',
                               'sequenceNum': 1005,
                               'slug': 'html__navgurukul-ka-brochure/part5',
                               'submissionType': None},
                              {'githubLink': 'https://github.com/navgurukul/newton/tree/master/html/navgurukul-ka-brochure/part6.md',
                               'id': 890,
                               'name': 'Place Six',
                               'parentExerciseId': 880,
                               'reviewType': 'peer',
                               'sequenceNum': 1006,
                               'slug': 'html__navgurukul-ka-brochure/part6',
                               'submissionType': None},
                              {'githubLink': 'https://github.com/navgurukul/newton/tree/master/html/navgurukul-ka-brochure/part7.md',
                               'id': 891,
                               'name': 'Part Seven',
                               'parentExerciseId': 880,
                               'reviewType': 'peer',
                               'sequenceNum': 1007,
                               'slug': 'html__navgurukul-ka-brochure/part7',
                               'submissionType': None}],
    'githubLink': 'https://github.com/navgurukul/newton/tree/master/html/navgurukul-ka-brochure/part0.md',
    'id': 880,
    'name': 'Brochure - Introduction',
    'parentExerciseId': 880,
    'reviewType': 'peer',
    'sequenceNum': 1000,
    'slug': 'html__navgurukul-ka-brochure/part0',
    'submissionType': None}